### ISSUE TITLE
UpdateTabNamePacket causing internal server error on player joining server

### ISSUE THREAD

**Issue by NeonCarbide** [FTBTeam/FTB-Essentials#16]
Currently using [ATM6 To The Sky 1.0.5](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6-to-the-sky-atm6s).

About 50% of the time when I, or one of my friends, tries to connect to my server, we get disconnected from an internal server error. Every time it happens, the same errors show up in the server log.

[Server Log](https://gist.github.com/NeonCarbide/7de4d5ffa4310096c08f1f69ebe208ba)

So far, the only fix I've found has been to keeping restarting the server until everyone is able to join.

I'm not exactly sure whether this is an issue with FTB Essentials, EventBus, or just a modpack issue, but this seems like the best place to start.

**Comment by TheTurbanator** [comment]
I'm having the same issue

[Server Log](https://gist.github.com/TheTurbanator/9bf247171dfc9c3f12c2a65909c13195)

restarting also fixes the issue

**Comment by MaxNeedsSnacks** [comment]
This seems to have been caused by a player with a `null` uuid, which should ***never ever*** happen unless it is a fake player (or the server uses offline mode?)

Either way, we've switched to a different system for packet management since then, please try to reproduce this again with newer mod versions and feel free to reopen if the issue persists
