### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by jrddunbr** [FTBTeam/FTB-Essentials#22]
Hi,

Your repository does not have a license indicated. The CurseForge website [here](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge) indicates All Rights Reserved, while your organization's website specifies LGPL [here](https://feed-the-beast.com/mods) (you may need to change pages and search the page for FTB to find it).

Can you please add the license here and correct the license on CurseForge if they are incorrect?

Thanks!

**Comment by MichaelHillcox** [comment]
Same as my other response but all FTB mods are visible source All Rights Reserved. If it's just a pack you're playing with a few friends and don't intend to release them you should be fine. If you want to release a pack, that's a different conversation. @LatvianModder can you confirm our rules on redistribution?

**Comment by jrddunbr** [comment]
Any updates on rules on redistribution? Also, should I create a backlog issue for your website/repository to update the license?

**Comment by MichaelHillcox** [comment]
We're updated our license on the website, what do you mean for redistribution? With an ARR, you will have to contract us for Permission, you can use any of our repos to ask for permission :D

**Comment by MaxNeedsSnacks** [comment]
Also, Mikey failed to mention this here, but due to the way CurseForge works, you may automatically __use__ any **released** versions of our mods (i.e. the binaries on CurseForge) __in any CurseForge packs__, without having to request explicit permission prior to that; it's only if you want to make a non-CF pack or use a non-public mod release that you will actually have to ask us for permission.

(Keep in mind that what I said above only applies to **redistribution within modpacks**, if you want to re-upload our JARs, for example to a Chinese Minecraft forum, you __will__ still have to ask us for permission first!)
