### ISSUE TITLE
Disable Commands?

### ISSUE THREAD

**Issue by Crazydude323** [FTBTeam/FTB-Essentials#7]
Just a suggestion, but I'd certainly like it if there were options to disable specific commands, in case you only want players on the server to have access to some of them.

**Comment by gzr529** [comment]
Hey, did you find a way to disable commands? Some players are abusing the RTP command and ruining the server performance.

**Comment by gzr529** [comment]
OK, I guess you can follow this thread and set all the values you want to zero. Like, if you don't want /sethome then set the number of max homes to zero. 

https://github.com/FTBTeam/FTB-Essentials/issues/3

**Comment by Crazydude323** [comment]
That doesn't work for all commands, though. Like /tpa for example.

**Comment by AyeAyeRonn707** [comment]
Following because I'd like to disable tpa

**Comment by XCOYoshi** [comment]
alle the things you sad are not working becouse my config issent working in all 3 locaitschons

**Comment by Rutes** [comment]
some way to disable /nickname would be great

**Comment by ChihoiTse** [comment]
I also think I need to disable the command feature.

**Comment by MoonMoonShark** [comment]
i've seen other mods like this where you can set restrictions by user level in the server, some things being available to everyone, some to OPs and higher, and some to only server owners. i think a system like that would be good, where, instead of simply deactivating a feature altogether, servers could have certain commands (like /fly or /rtp) available for OPs, but not regular players.

**Comment by NillerMedDild** [comment]
This might be a thing already actually, looks like FTB Ranks can be used to disable/enable/restrict commands to certain players.

**Comment by MaxNeedsSnacks** [comment]
Most commands now have an individual on-off toggle to enable / disable them
